languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Marius Codes"
#logo = "images/avatar/avatar.jpeg"
description = "Marius Codes"
copyright = "© 2022 Marius Kimmina"

dateFormat = "2 January 2006"

[author]
  name = "Marius Kimmina"
  image = "images/avatar/avatar4.jpeg"
  headline = "Software Engineer"
  bio = "Software Engineer"
  links = [
     { github = "https://github.com/mariuskimmina" },
     { linkedin = "https://linkedin.com/in/marius-kimmina" },
  ]
