baseURL: "https://mariuskimmina.com/"
languageCode: "en-us"
title: "Marius Kimmina"
theme: "blowfish"

menu:
  main:
  - identifier: blog
    name: Blog
    url: /blog/
    weight: 10
  - identifier: hacks
    name: Hacks
    url: /hacks/
    weight: 20
  - identifier: projects
    name: Projects
    url: /projects
    weight: 40
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 50


params:
  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/mariuskimmina"
    - name: "github"
      url: "https://github.com/mariuskimmina"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/marius-kimmina/"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/13693791"
    - name: "goodreads"
      url: "https://goodreads.com/mariuskimmina"
    - name: "hackthebox"
      url: "https://app.hackthebox.com/profile/36525"
  profileMode:
    enabled: true
    subtitle: "Trying Failing Learning"
    imageUrl: "/profile/pic4.jpg" # optional
    imageTitle: "Marius Kimmina" # optional
      #imageWidth: 120 # custom size
      #imageHeight: 120 # custom size
    buttons:
      - name: About
        url: "/about"
          
